//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReposEntities : DbContext
    {
        public ReposEntities()
            : base("name=ReposEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ConsoleUser> ConsoleUsers { get; set; }
        public DbSet<DataLocation> DataLocations { get; set; }
        public DbSet<Host> Hosts { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<JobRun> JobRuns { get; set; }
        public DbSet<JobRunDataLocation> JobRunDataLocations { get; set; }
        public DbSet<JobRunStatu> JobRunStatus { get; set; }
        public DbSet<LoginRecord> LoginRecords { get; set; }
        public DbSet<Project> Projects { get; set; }
    }
}
