//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLocation
    {
        public DataLocation()
        {
            this.JobRunDataLocations = new HashSet<JobRunDataLocation>();
        }
    
        public int locationID { get; set; }
        public string DataStoreName { get; set; }
    
        public virtual ICollection<JobRunDataLocation> JobRunDataLocations { get; set; }
    }
}
