//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        public Host()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int HostID { get; set; }
        public string HostName { get; set; }
        public string PhysicalAddress { get; set; }
        public string OS { get; set; }
        public Nullable<int> Memory { get; set; }
        public Nullable<int> FreeMemory { get; set; }
        public Nullable<System.DateTime> LastMonActivity { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
