//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobRuns = new HashSet<JobRun>();
        }
    
        public string JobID { get; set; }
        public long fk_ProjectID { get; set; }
        public string JobName { get; set; }
        public string LocalPath { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<JobRun> JobRuns { get; set; }
    }
}
