//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRunDataLocation
    {
        public int JobRunDataStoreID { get; set; }
        public string JobRunID { get; set; }
        public int DataLocatorID { get; set; }
        public int isSource { get; set; }
        public int isTarget { get; set; }
        public byte[] updateTime { get; set; }
    
        public virtual DataLocation DataLocation { get; set; }
        public virtual JobRun JobRun { get; set; }
    }
}
