//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRecord
    {
        public long LoginRecordID { get; set; }
        public Nullable<int> fk_CosoleUserID { get; set; }
        public string acessTime { get; set; }
    
        public virtual ConsoleUser ConsoleUser { get; set; }
    }
}
