//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngMonAppConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public long ProjectID { get; set; }
        public Nullable<int> fk_HostID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectPath { get; set; }
    
        public virtual Host Host { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
